# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TP2-IoT

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_WEBAPP_NAME: TP2-IoT   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './tp2_ash_jason'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.15.0'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ./tp2_ash_jason
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_866167E0966543F5A744433831551869 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
